# Generated by Django 6.0.4 on 2026-09-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_username',
            field=models.CharField(blank=True, help_text='Your exact GitHub username. Required to track your project contributions.', max_length=100, null=True),
        ),
    ]
