# Generated by Django 6.0.3 on 2026-09-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_alter_coursesection_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='responsibilities',
            field=models.TextField(blank=True, default='', verbose_name='Documented Responsibilities'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_in_team',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Individual Project Role'),
        ),
    ]
