# Generated by Django 6.0.4 on 2026-09-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_coursesection_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='github_repo_url',
            field=models.URLField(blank=True, help_text='Format: https://github.com/username/repository', max_length=255, null=True),
        ),
    ]
