# Generated by Django 6.0.3 on 2026-10-06 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_team_github_repo_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NonCodingDeliverable',
            fields=[
                ('deliverable_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='e.g., Figma Design, SRS Document', max_length=255)),
                ('link', models.URLField(help_text='Must be a valid URL starting with http:// or https://', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='academic.team')),
            ],
        ),
    ]
