# Generated by Django 6.0.3 on 2026-10-07 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_deliverablecontribution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Technical Contribution, Communication, Punctuality', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional breakdown of what this criterion means')),
                ('max_score', models.IntegerField(default=5, help_text='Maximum possible score (default is 5)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_criteria', to='academic.project')),
            ],
        ),
        migrations.CreateModel(
            name='PeerEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_feedback', models.TextField(blank=True, help_text='Anonymous text feedback for the teammate')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('evaluatee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_received', to=settings.AUTH_USER_MODEL)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_given', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='academic.team')),
            ],
            options={
                'unique_together': {('team', 'evaluator', 'evaluatee')},
            },
        ),
        migrations.CreateModel(
            name='PeerEvaluationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.evaluationcriterion')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='academic.peerevaluation')),
            ],
            options={
                'unique_together': {('evaluation', 'criterion')},
            },
        ),
    ]
